[version]
current = "2.0.0"

regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  (
    (?P<lifecycle>a|b|rc|\.post)
    (?P<release>\d+)
  )?
'''

[git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"

[[file]]
src = "setup.py"
search = "VERSION = "

[[file]]
src = "enchant/__init__.py"
search = "__version__ = "

# You can specify a list of commands to
# run after the files have been patched
# and before the git commit is made

#  [[before_commit]]
#  name = "check changelog"
#  cmd = "grep -q {current_version} Changelog.md"

# Or run some commands after the git tag and the branch
# have been pushed:
#  [[after_push]]
#  name = "check changelog"
#  cmd = "grep -q {current_version} Changelog.md"
